### ISSUE TITLE
Porting from Spreadsheet::XLSX to Spreadsheet::ParseXLSX

### ISSUE THREAD

**Issue by rossy62** [doy/spreadsheet-parsexlsx#40]
Hi All,
I'm not sure if this is a bug, but I'm looking for a solution.
The behavior on encountering an empty cell is different between Spreadsheet::XLSX and Spreadsheet::ParseXLSX.  I'm unfamiliar with the original ParseExcel behavior, so thought I would ask the experts, and just log this difference in behavior for others who might be porting to the newer module.  I find Spreadsheet::ParseXLSX to be superior in that it doesn't throw warnings at formulas that it encounters.  But I'm having difficulty do to the difference in how empty cells are treated.

In Spreadsheet::XLSX, an empty cell selected by:

$Cell = $sheet -> {Cells} [$row] [$col];

If this is empty Spreadsheet::XLSX would set $Cell such that
next if (!$Cell);    Would allow advancing to the next row.

Now, with ParseXLSX I'm getting notification that the cell is not empty. (Likely it's formatted?), anyway, I'm falling into code that is expecting values to be present, and there are no values.

I'm getting a valid cell, but need a way to test if the cell is empty.

I'm not 100% sure that compatibility with Spreadsheet::XLSX is desirable, what does the original Spreadsheet::ParseExcel do with an empty cell?

**Comment by doy** [comment]
Yeah, Spreadsheet::ParseXLSX aims for compatibility with Spreadsheet::ParseExcel and not Spreadsheet::XLSX. This issue is in general because Spreadsheet::ParseXLSX (and Spreadsheet::ParseExcel) use objects for cell contents, while Spreadsheet::XLSX just returns the string value (and yeah, if a cell has formatting but no value, it will still return that object). Checking `$Cell->value` instead should work - you can read more about this in the docs for Spreadsheet::ParseExcel::Cell.
